import {
  Search,
  Image as ImageIcon,
  FileText,
  Settings,
  Maximize,
  PenTool,
  Edit3,
  Fingerprint,
  RefreshCw,
  FlipHorizontal,
  Crop,
  Type,
  Layers as LayersIcon,
  Mail,
  Building,
  Calculator,
  Smartphone,
  Video,
  Instagram,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

export type ToolCategory =
  | "Format"
  | "Image Utility"
  | "PDF Utility"
  | "India Post"
  | "Generators"
  | "Payments"
  | "Education"
  | "Video Utility";

export type ToolEntry = {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  accent: string;
  bg: string;
  border: string;
  href: string;
};

export const TOOLS_DATA: ToolEntry[] = [
  {
    id: "ssc",
    name: "SSC Exam Signature",
    description: "Format signature for all SSC examination platforms with official compliance",
    category: "Format",
    icon: PenTool,
    accent: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/20",
    href: "/tools/ssc",
  },
  {
    id: "rrb",
    name: "RRB Railway Signature",
    description: "Format signature for RRB Railway recruitment examinations with handwriting emphasis",
    category: "Format",
    icon: Edit3,
    accent: "text-pink-400",
    bg: "bg-pink-400/10",
    border: "border-pink-400/20",
    href: "/tools/rrb",
  },
  {
    id: "india-post-photo",
    name: "India Post GDS Photo",
    description: "Format photo for India Post GDS Online Engagement with portrait orientation",
    category: "India Post",
    icon: ImageIcon,
    accent: "text-sky-400",
    bg: "bg-sky-400/10",
    border: "border-sky-400/20",
    href: "/tools/india-post-photo",
  },
  {
    id: "india-post-signature",
    name: "India Post GDS Signature",
    description: "Format signature for India Post GDS Online Engagement with landscape orientation",
    category: "India Post",
    icon: PenTool,
    accent: "text-cyan-400",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/20",
    href: "/tools/india-post-signature",
  },
  {
    id: "bank-thumb",
    name: "Banking Thumb Impression",
    description: "Format left-thumb impression for banking recruitments with square ratio and clarity optimization",
    category: "Format",
    icon: Fingerprint,
    accent: "text-violet-400",
    bg: "bg-violet-400/10",
    border: "border-violet-400/20",
    href: "/tools/bank-thumb",
  },
  {
    id: "ibps-declaration",
    name: "IBPS Declaration",
    description: "Prepare handwritten declaration image for IBPS portals with exact landscape output profile",
    category: "Format",
    icon: FileText,
    accent: "text-emerald-400",
    bg: "bg-emerald-400/10",
    border: "border-emerald-400/20",
    href: "/tools/ibps-declaration",
  },
  {
    id: "neet-signature",
    name: "NEET Signature",
    description: "Format NEET signature image with balanced compression and official upload-friendly dimensions",
    category: "Format",
    icon: PenTool,
    accent: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/20",
    href: "/tools/neet-signature",
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize with presets, fit modes, background fill, quality control, and export format switching",
    category: "Image Utility",
    icon: Maximize,
    accent: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/20",
    href: "/tools/image-resizer",
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Reduce file size with output format conversion, size targeting, scaling, and width constraints",
    category: "Image Utility",
    icon: Settings,
    accent: "text-fuchsia-400",
    bg: "bg-fuchsia-400/10",
    border: "border-fuchsia-400/20",
    href: "/tools/image-compressor",
  },
  {
    id: "aspect-ratio-changer",
    name: "Aspect Ratio Changer",
    description: "Convert ratios with cover or contain framing, custom backgrounds, presets, and export format control",
    category: "Image Utility",
    icon: Maximize,
    accent: "text-sky-400",
    bg: "bg-sky-400/10",
    border: "border-sky-400/20",
    href: "/tools/aspect-ratio-changer",
  },
  {
    id: "pdf-maker",
    name: "PDF Maker",
    description: "Build PDFs with page size, orientation, margins, fit mode, compression level, and file naming controls",
    category: "PDF Utility",
    icon: FileText,
    accent: "text-rose-400",
    bg: "bg-rose-400/10",
    border: "border-rose-400/20",
    href: "/tools/pdf-maker",
  },
  {
    id: "pdf-editor",
    name: "Pro PDF Editor",
    description: "Edit, whiteout, annotate, and natively bake interactive text into any PDF without server uploads.",
    category: "PDF Utility",
    icon: FileText,
    accent: "text-indigo-400",
    bg: "bg-indigo-400/10",
    border: "border-indigo-400/20",
    href: "/tools/pdf-editor",
  },
  {
    id: "image-scanner",
    name: "Image Scanner",
    description: "Create scan outputs with black-and-white, grayscale, cleanup, invert, and export format modes",
    category: "Image Utility",
    icon: Search,
    accent: "text-indigo-400",
    bg: "bg-indigo-400/10",
    border: "border-indigo-400/20",
    href: "/tools/image-scanner",
  },
  {
    id: "image-format-converter",
    name: "Image Format Converter",
    description: "Convert JPG, PNG, and WEBP files with quality control, background fill, and export sizing",
    category: "Image Utility",
    icon: RefreshCw,
    accent: "text-amber-400",
    bg: "bg-amber-400/10",
    border: "border-amber-400/20",
    href: "/tools/image-format-converter",
  },
  {
    id: "image-rotate-flip",
    name: "Image Rotate & Flip",
    description: "Rotate, mirror, and export images with background control and angle presets",
    category: "Image Utility",
    icon: FlipHorizontal,
    accent: "text-teal-400",
    bg: "bg-teal-400/10",
    border: "border-teal-400/20",
    href: "/tools/image-rotate-flip",
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Center-crop images to common or custom aspect ratios with export size and format controls",
    category: "Image Utility",
    icon: Crop,
    accent: "text-pink-400",
    bg: "bg-pink-400/10",
    border: "border-pink-400/20",
    href: "/tools/image-cropper",
  },
  {
    id: "watermark-stamper",
    name: "Watermark Stamper",
    description: "Apply text watermarks with position, opacity, color, and output format settings",
    category: "Image Utility",
    icon: Type,
    accent: "text-sky-400",
    bg: "bg-sky-400/10",
    border: "border-sky-400/20",
    href: "/tools/watermark-stamper",
  },
  {
    id: "bulk-image-converter",
    name: "Bulk Image Converter",
    description: "Convert multiple images in one run with target format and quality controls",
    category: "Image Utility",
    icon: LayersIcon,
    accent: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/20",
    href: "/tools/bulk-image-converter",
  },
  {
    id: "typing-tutor",
    name: "Typing Tutor",
    description: "Beginner to advanced typing learner with SSC CGL exam prep and dynamic shortfall analysis.",
    category: "Education",
    icon: Type,
    accent: "text-blue-400",
    bg: "bg-blue-400/10",
    border: "border-blue-400/20",
    href: "/tools/typing-tutor",
  },
  {
    id: "letterpad-generator",
    name: "Letterpad Generator",
    description: "Create professionally formatted government & office letterpads with AI assistance, customizable templates, and PDF output",
    category: "Generators",
    icon: Mail,
    accent: "text-pink-400",
    bg: "bg-pink-400/10",
    border: "border-pink-400/20",
    href: "/tools/letterpad-generator",
  },
  {
    id: "gds-leave",
    name: "GDS Leave Application",
    description: "Generate official GDS Leave Applications in quadruplicate format — Paid Leave or LWA — with cover letter, auto-filled fields, and print-ready PDF output",
    category: "India Post",
    icon: Building,
    accent: "text-amber-400",
    bg: "bg-amber-400/10",
    border: "border-amber-400/20",
    href: "/tools/gds-leave",
  },
  {
    id: "td-commission",
    name: "TD Commission / BPM",
    description: "Generate official BPM Incentive Bills for Time Deposit (TD) commissions with auto-calculating rates, amounts, and PDF exports",
    category: "India Post",
    icon: Calculator,
    accent: "text-emerald-400",
    bg: "bg-emerald-400/10",
    border: "border-emerald-400/20",
    href: "/tools/td-commission",
  },
  {
    id: "upi-qr",
    name: "UPI QR Generator",
    description: "Generate premium glassmorphic UPI QR codes for payments with SW Info Systems branding.",
    category: "Payments",
    icon: Smartphone,
    accent: "text-green-400",
    bg: "bg-green-400/10",
    border: "border-green-400/20",
    href: "/tools/upi-qr",
  },
  {
    id: "youtube-stats",
    name: "YouTube Stats Extractor",
    description: "Analyze video performance, extract SEO tags, and get channel insights for any YouTube video.",
    category: "Video Utility",
    icon: Video,
    accent: "text-red-400",
    bg: "bg-red-400/10",
    border: "border-red-400/20",
    href: "/tools/youtube-stats",
  },
  {
    id: "instagram-downloader",
    name: "Instagram Media Downloader",
    description: "Extract high-quality images and videos from Instagram posts and reels with ease.",
    category: "Video Utility",
    icon: Instagram,
    accent: "text-pink-400",
    bg: "bg-pink-400/10",
    border: "border-pink-400/20",
    href: "/tools/instagram-downloader",
  },
];

export const CATEGORIES = [
  "All",
  "Format",
  "Image Utility",
  "PDF Utility",
  "India Post",
  "Generators",
  "Payments",
  "Education",
  "Video Utility",
] as const;
