-- SW TOOLS STABILIZATION SCRIPT
-- This script ensures all required tables exist and basic configuration is seeded.
-- Run this in your Supabase SQL Editor if you encounter missing table errors.

-- 1. PROFILES Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    wallet_balance INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. USAGE_LOGS Table (For credit tracking)
CREATE TABLE IF NOT EXISTS public.usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    tool_id TEXT NOT NULL,
    credits_spent INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. USER_FILES Table (For saving generated documents)
CREATE TABLE IF NOT EXISTS public.user_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    tool_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    storage_path TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. SYSTEM_CONFIG Table (For tool costs and packages)
CREATE TABLE IF NOT EXISTS public.system_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. SEED INITIAL CONFIG (IF MISSING)
INSERT INTO public.system_config (key, value)
VALUES 
('tool_costs', '{"letterpad_generator": 10, "td_commission": 15, "gds_leave": 10, "letterpad_ai_fill": 5}'),
('credit_packages', '[
    {"credits": 100, "price": 99},
    {"credits": 500, "price": 399},
    {"credits": 1500, "price": 999}
]')
ON CONFLICT (key) DO NOTHING;

-- 6. ENABLE RLS (Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config ENABLE ROW LEVEL SECURITY;

-- 7. POLICIES (Allow users to see their own data)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own profile') THEN
        CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own usage logs') THEN
        CREATE POLICY "Users can view own usage logs" ON public.usage_logs FOR SELECT USING (auth.uid() = user_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Everyone can view system config') THEN
        CREATE POLICY "Everyone can view system config" ON public.system_config FOR SELECT USING (true);
    END IF;
END $$;
